### ISSUE TITLE
클리앙 idate 이슈

### ISSUE THREAD

**Issue by soonyoungcheon** [Makeshiftshelter01/Mater#15]
클리앙 스크롤 시 idate의 태그를 맞게 해줬으나 정보를 가져오지 못하는 현상 발생

fillblanks 값만 들어있음

**Comment by ul8ksgdmy** [comment]
태그를 확인했더니 시간을 가져오는 게 매우 복잡하게 꼬여있었네요.
ini 파일의 idate를 div.post_author span:first-child로 변경해서 가져올 수 있도록 바꿨습니다~

**Comment by ul8ksgdmy** [comment]
사이트의 html을 확인했더니 시간을 보여주는 부분의 태그가 혼동하기 쉽게 되어 있었음.
ini 파일의 idate를 div.post_author span:first-child로 변경해서 가져올 수 있도록 수정.
